In [ ]:
import numpy as np

In [ ]:
random_number = np.random.randn(10)
print(random_number)

[ 1.07144359 -0.69522247  1.84344587  2.38731272  0.75693655 -0.83375547
  0.57551489 -0.08500776  0.23549267  0.51681225]


In [ ]:
random_number > 0.5

array([ True, False,  True,  True,  True, False,  True, False, False,
        True])

In [ ]:
random_number >= 0.5

array([ True, False,  True,  True,  True, False,  True, False, False,
        True])

# Boolean Selection

In [ ]:
random_number

array([ 1.07144359, -0.69522247,  1.84344587,  2.38731272,  0.75693655,
       -0.83375547,  0.57551489, -0.08500776,  0.23549267,  0.51681225])

In [ ]:
random_number < 1

array([False,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
random_number[[False,  True, False, False,  True,  True,  True,  True,  True,True]]

array([-0.69522247,  0.75693655, -0.83375547,  0.57551489, -0.08500776,
        0.23549267,  0.51681225])

In [ ]:
random_number[[False,  True, False, False,  True,  True,True,True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 8

#Masking

In [ ]:
random_number[ random_number<1 ]

array([-0.69522247,  0.75693655, -0.83375547,  0.57551489, -0.08500776,
        0.23549267,  0.51681225])

In [ ]:
arr1d = np.array([2,5,7,11,34,23,0,67,56,89])

In [ ]:
arr1d

array([ 2,  5,  7, 11, 34, 23,  0, 67, 56, 89])

In [ ]:
arr1d[ arr1d>10 ]

array([11, 34, 23, 67, 56, 89])

In [ ]:
arr1d[(arr1d >=10) & (arr1d<=50)]

array([11, 34, 23])

In [ ]:
arr2d = np.arange(36).reshape(6,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
arr2d.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
# we dont need to know how many nunber of elements in array its convert in 1d
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
arr3d = np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [ ]:
arr3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
arr3d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
ravelled = arr3d.ravel()

In [ ]:
ravelled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
ravelled[4:10] = 10000

In [ ]:
ravelled

array([    0,     1,     2,     3, 10000, 10000, 10000, 10000, 10000,
       10000,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [ ]:
arr3d

array([[[    0,     1,     2,     3],
        [10000, 10000, 10000, 10000],
        [10000, 10000,    10,    11],
        [   12,    13,    14,    15]],

       [[   16,    17,    18,    19],
        [   20,    21,    22,    23],
        [   24,    25,    26,    27],
        [   28,    29,    30,    31]],

       [[   32,    33,    34,    35],
        [   36,    37,    38,    39],
        [   40,    41,    42,    43],
        [   44,    45,    46,    47]],

       [[   48,    49,    50,    51],
        [   52,    53,    54,    55],
        [   56,    57,    58,    59],
        [   60,    61,    62,    63]]])

In [ ]:
flattened = arr3d.flatten()

In [ ]:
flattened

array([    0,     1,     2,     3, 10000, 10000, 10000, 10000, 10000,
       10000,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63])

In [ ]:
flattened[4:10] = [4,5,6,7,8,9]

In [ ]:
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
arr3d

array([[[    0,     1,     2,     3],
        [10000, 10000, 10000, 10000],
        [10000, 10000,    10,    11],
        [   12,    13,    14,    15]],

       [[   16,    17,    18,    19],
        [   20,    21,    22,    23],
        [   24,    25,    26,    27],
        [   28,    29,    30,    31]],

       [[   32,    33,    34,    35],
        [   36,    37,    38,    39],
        [   40,    41,    42,    43],
        [   44,    45,    46,    47]],

       [[   48,    49,    50,    51],
        [   52,    53,    54,    55],
        [   56,    57,    58,    59],
        [   60,    61,    62,    63]]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones_like(arr3d)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros_like(arr3d)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.full((5,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
arr = np.array([4,5,6,7])

In [ ]:
arr.astype('float')

array([4., 5., 6., 7.])