#Combining Arrays

In [1]:
import numpy as np
a = np.zeros((4,4))
b = np.ones((4,4))

In [2]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [5]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.dstack((a,b))

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [7]:
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
x = np.dstack((a,b))

In [13]:
x

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [12]:
x.shape

(4, 4, 2)

In [16]:
np.concatenate((a,b),axis=1) # increase columns

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [17]:
np.concatenate((a,b),axis=0) # increase rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
np.column_stack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [19]:
np.row_stack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

```
hstack == column_stack == axis=1
vstack == row_stack    == axis=0
```

#Spliting Arrays

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [26]:
np.split(a, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [27]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [28]:
a.mean(), a.var(), a.std()

(7.5, 21.25, 4.6097722286464435)

#Fancy Indexing

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a[:,3:]

array([[ 3],
       [ 7],
       [11],
       [15]])

In [31]:
a[[3,0,2]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [32]:
a[:, [3,1,0]]

array([[ 3,  1,  0],
       [ 7,  5,  4],
       [11,  9,  8],
       [15, 13, 12]])

In [33]:
a.T, a.transpose()

(array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]),
 array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]))

In [34]:
a = np.array([2.9, 2.1, 3.5])

In [35]:
np.ceil(a)

array([3., 3., 4.])

In [36]:
np.floor(a)

array([2., 2., 3.])

#Miror Operations

In [41]:
w = np.arange(16).reshape(4,4)
z = np.arange(16,32).reshape(4,4)
t = np.arange(12).reshape(3,4)

In [38]:
w.shape

(4, 4)

In [39]:
z.shape

(4, 4)

In [42]:
t.shape

(3, 4)

In [40]:
w * z

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [43]:
w + t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [44]:
w * t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [45]:
w@z

array([[ 152,  158,  164,  170],
       [ 504,  526,  548,  570],
       [ 856,  894,  932,  970],
       [1208, 1262, 1316, 1370]])