#Combining Arrays

In [1]:
import numpy as np
a = np.zeros((4,4))
b = np.ones((4,4))

In [ ]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.dstack((a,b))

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
x = np.dstack((a,b))

In [ ]:
x

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [ ]:
x.shape

(4, 4, 2)

In [ ]:
np.concatenate((a,b),axis=1) # increase columns

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [ ]:
np.concatenate((a,b),axis=0) # increase rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
np.column_stack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [ ]:
np.row_stack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

```
hstack == column_stack == axis=1
vstack == row_stack    == axis=0
```

#Spliting Arrays

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.split(a, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
a.mean(), a.var(), a.std()

(7.5, 21.25, 4.6097722286464435)

#Fancy Indexing

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a[:,3:]

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
a[[3,0,2]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
a[:, [3,1,0]]

array([[ 3,  1,  0],
       [ 7,  5,  4],
       [11,  9,  8],
       [15, 13, 12]])

In [ ]:
a.T, a.transpose()

(array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]),
 array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]))

In [ ]:
a = np.array([2.9, 2.1, 3.5])

In [ ]:
np.ceil(a)

array([3., 3., 4.])

In [ ]:
np.floor(a)

array([2., 2., 3.])

#Miror Operations

In [ ]:
w = np.arange(16).reshape(4,4)
z = np.arange(16,32).reshape(4,4)
t = np.arange(12).reshape(3,4)

In [ ]:
w.shape

(4, 4)

In [ ]:
z.shape

(4, 4)

In [ ]:
t.shape

(3, 4)

In [ ]:
w * z

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [ ]:
w + t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [ ]:
w * t

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [ ]:
w@z

array([[ 152,  158,  164,  170],
       [ 504,  526,  548,  570],
       [ 856,  894,  932,  970],
       [1208, 1262, 1316, 1370]])

In [2]:
from numpy.linalg import inv, qr

In [3]:
x = np.random.randn(5,5)
x

array([[-0.83590674,  2.16913826,  0.08287619,  0.97906295,  1.17420557],
       [ 0.78019042, -0.51959545,  0.52371177,  0.93189458,  0.08083345],
       [-0.19542552,  0.93088837, -0.83808743,  0.20258783,  1.37437049],
       [-0.83126084,  0.94145727, -0.01420832,  0.35430456, -0.41694802],
       [ 0.44750838, -1.71725269, -0.34366325, -1.1834194 , -0.71025358]])

In [4]:
x_inv = inv(x)
x_inv

array([[-5.21829402, -2.20470902,  0.76670976, -1.66086141, -6.41929599],
       [-3.60503228, -2.09573162,  0.35631921, -1.05718632, -4.88832147],
       [ 2.21145242,  0.18063774, -1.4381154 , -0.9384432 ,  1.44466709],
       [ 0.86255935,  1.56335391,  0.39445331,  1.35374687,  1.57250343],
       [ 2.9211492 ,  0.98569457, -0.33981859, -0.29191717,  3.04734033]])

In [5]:
x@x_inv

array([[ 1.00000000e+00,  2.60633591e-16,  2.79038045e-18,
        -2.16367267e-16, -1.16259666e-15],
       [-1.26755550e-15,  1.00000000e+00,  2.31629721e-16,
        -3.70570626e-16, -1.85557166e-15],
       [ 4.31882798e-16,  1.87446740e-16,  1.00000000e+00,
         5.48344851e-17,  7.76273312e-17],
       [-9.34802557e-16,  2.44550394e-16, -1.64176997e-16,
         1.00000000e+00, -1.01980840e-15],
       [ 3.82832791e-16,  2.10905097e-16,  8.41758222e-17,
         4.50147585e-16,  1.00000000e+00]])

In [6]:
a = np.array([1.234, 5.345, 7.8])

In [7]:
np.modf(a)

(array([0.234, 0.345, 0.8  ]), array([1., 5., 7.]))

In [8]:
qr(x)

QRResult(Q=array([[-0.55890223, -0.42170832,  0.1299322 ,  0.2088064 ,  0.67030433],
       [ 0.52164929, -0.52291727,  0.2887661 , -0.5655924 ,  0.22618336],
       [-0.130665  , -0.35666435, -0.88081953, -0.2716501 , -0.0779768 ],
       [-0.5557959 ,  0.32094759,  0.18686531, -0.74072797, -0.06698506],
       [ 0.29921212,  0.56436052, -0.29827852, -0.11846273,  0.6992609 ]]), R=array([[ 1.49562249, -2.64209824,  0.2414516 , -0.6385639 , -0.77446001],
       [ 0.        , -1.64204411, -0.2084017 , -1.52660062, -1.56228797],
       [ 0.        ,  0.        ,  1.00005459,  0.63706388, -0.90072303],
       [ 0.        ,  0.        ,  0.        , -0.49992309,  0.21909861],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.22946597]]))

#Broadcasting

In [9]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
y = np.arange(4)
4

4

In [12]:
x + y

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])